### ISSUE TITLE
SingleStorageSchedule.__init__ should have a storage type argument

### ISSUE THREAD

**Issue by jrmaddison** [firedrakeproject/checkpoint_schedules#13]

**Comment by Ig-dolci** [comment]
Done. It is at the dolci/issues branch.

**Comment by jrmaddison** [comment]
I think the `storage` argument should have a default value of `StorageType.RAM`.

**Comment by Ig-dolci** [comment]
Done. def __init__(self, storage=StorageType.RAM):

**Comment by Ig-dolci** [comment]
SingleStorageSchedule.__init__ default storage argument was moved to storage=StorageType.WORK.
