### ISSUE TITLE
Adjoint dependency data should not be stored in RAM storage type

### ISSUE THREAD

**Issue by jrmaddison** [firedrakeproject/checkpoint_schedules#20]
e.g. in a multi-stage schedule the forward ahead of a reverse currently uses

`Forward(3, 4, False, True, 'RAM')`

I think this should instead write to a 'working memory' storage type. This distinguishes between 'RAM' as a storage location for data to be later loaded, and a 'working memory' location to be retained e.g. for use by the adjoint in a following `Reverse` action.

**Comment by Ig-dolci** [comment]
Done.
