### ISSUE TITLE
Adding an example of using the package in practice

### ISSUE THREAD

**Issue by matt-graham** [firedrakeproject/checkpoint_schedules#55]
Raising as part of JOSS review https://github.com/openjournals/joss-reviews/issues/6148

The tutorial example in https://github.com/firedrakeproject/checkpoint_schedules/blob/main/docs/notebooks/tutorial.ipynb is great at giving an understanding of the packages's API and an overview of the different checkpoint schedule algorithms implemented, however it would also be useful to have an example of how the package can be used in practice in actual adjoint computation, even if it's for a trivial problem / forward computation.

The paper indicates the package has been incoroporated in to `tlm_adjoint` (presumably once https://github.com/tlm-adjoint/tlm_adjoint/pull/382 is merged in?) - even just linking to how the package is used there as a 'next steps' tutorial example could be useful.

**Comment by Ig-dolci** [comment]
@matt-graham We appreciate your suggestion to include an example application in our documentation. 

Following your suggestion and seeking to make the usage of `checkpoint_schedules` more accessible, we have included an example of checkpoint_schedules usage in an adjoint-based gradient problem. You can access it in the following notebook: [checkpoint_schedule application: Adjoint-Based Gradient with the Burger's Equation](https://github.com/firedrakeproject/checkpoint_schedules/blob/main/docs/notebooks/burger.ipynb). 

We are also pleased to inform you that checkpoint_schedules is now incorporated into the pyadjoint package (PR [121](https://github.com/dolfin-adjoint/pyadjoint/pull/121)).

**Comment by matt-graham** [comment]
@Ig-dolci - thanks the new notebook is fantastic!
